Fix TypeScript Error in `isConstructor` (#412)
* Fix TS error

node_modules/laravel-echo/src/util/index.ts:5:13 - error TS18046: 'err' is of type 'unknown'.

* Refactor to not use Reflect.construct to reduce chance on breaking change

* Update index.ts