Check for jQuery.ajax before jQuery.ajaxSetup
Only do jQuery.ajaxSetup if jQuery.ajax is available. It could be that jquery slim is available which does not include the ajax module. Otherwise a "Uncaught TypeError: jQuery.ajaxSetup is not a function" error is thrown and it all comes crashing down.